import { contextBridge, ipcRenderer } from 'electron';
import type { OfficeAPI } from '../shared/types.js';
async function request<T>(channel:string,input?:unknown):Promise<T>{const result=await ipcRenderer.invoke(channel,input);if(!result?.ok)throw new Error(result?.error||'The desktop request failed.');return result.value as T;}
const api:OfficeAPI={
 chooseProjectFolder:()=>request('office:project-folder'),chooseInputFiles:localFolder=>request('office:choose-input-files',localFolder),openProjectFolder:id=>request('office:project-open-folder',id),
 scanClaudeUsage:chooseFolder=>request('office:claude-local-usage',chooseFolder),changeAgentEffort:input=>request('office:agent-effort',input),changeAgentModel:input=>request('office:agent-model',input),getWorkLogs:()=>request('office:work-logs'),importWorkLogs:agentId=>request('office:work-log-import',agentId),
 bindAgentConnection:input=>request('office:agent-bind',input),
 connectAgent:draft=>request('office:agent-connect',draft),confirmAgent:ticket=>request('office:agent-confirm',ticket),cancelAgent:()=>request('office:agent-cancel'),
 connectionStatus:provider=>request('office:connection-status',provider),loginProvider:provider=>request('office:provider-login',provider),selectProviderTool:provider=>request('office:provider-tool',provider),openProviderUsage:provider=>request('office:provider-usage',provider),
 prepareRequest:input=>request('office:request-prepare',input),handoffPlan:input=>request('office:request-plan',input),
 discardPreparation:input=>request('office:request-discard-preparation',input),
 openHandoffTerminal:input=>request('office:request-handoff',input),observeJob:input=>request('office:request-observe',input),
 cancelJob:input=>request('office:request-cancel-job',input),linkJobSession:input=>request('office:request-link',input),
 verifyCloudTransport:input=>request('office:verify-transport',input),
 officeChatPage:input=>request('office:chat-page',input),
 historyPage:input=>request('office:history-page',input),logPage:input=>request('office:log-page',input),jobEventPage:input=>request('office:job-events',input),
 appliedReports:input=>request('office:applied-reports',input),localSessionSummary:jobId=>request('office:local-session-summary',jobId),
 localLaunchPlan:jobId=>request('office:local-launch-plan',jobId),localSessionArchive:assignmentId=>request('office:local-session-archive',assignmentId),
 migrateLegacyRecords:()=>request('office:migrate-legacy'),
 getState:()=>request('office:state'),getInfo:()=>request('office:info'),
 messagePage:input=>request('office:message-page',input),researchPage:input=>request('office:research-page',input),
 researchInsights:input=>request('office:research-insights',input),exportResearch:input=>request('office:research-export',input),
 command:command=>request('office:command',command),
 importFiles:input=>request('office:import',input),previewArtifact:id=>request('office:preview',id),
 exportProject:id=>request('office:export',id),backupWorkspace:()=>request('office:backup'),
 restoreWorkspace:()=>request('office:restore'),
 describeObject:input=>request('office:evidence-describe',input),readObject:input=>request('office:evidence-read',input),
 queryEvidence:input=>request('office:evidence-query',input),stagePacket:input=>request('office:evidence-packet',input),
 researchStatus:input=>request('office:research-status',input),
 assignResearchFunction:input=>request('office:research-assign-function',input),
 migrateResearchFunctions:input=>request('office:research-migrate-functions',input),
 pipelineAction:input=>request('office:pipeline',input),
 onChanged(callback){const handler=()=>callback();ipcRenderer.on('office:changed',handler);return()=>ipcRenderer.removeListener('office:changed',handler);},
};
contextBridge.exposeInMainWorld('office',api);
